In [1]:
%matplotlib inline

In [2]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt

from IPython.display import clear_output
from torch.utils.data import DataLoader, TensorDataset
from torchsummary import summary
from sklearn.model_selection import train_test_split

from data_generator import DataGen

In [3]:
class MMC(nn.Module):
    
    def __init__(self, beta=5, num_iter=20):
        super(MMC, self).__init__()
        self.df = 1. / beta
        self.num_iter = num_iter
        self.weights = nn.Parameter(data= torch.tensor([[1, self.df, 0], [-1, 0, 1], [0, 0, 1]]),
                                    requires_grad=False)
        # self.weights = nn.Parameter(data=torch.from_numpy(self._init_weights()).float(), 
        #                             requires_grad=False)
    
    def _init_weights(self):
        w = np.array([[1, self.df, 0], [-1, 0, 1], [0, 0, 1]])
        return np.broadcast_to(w, (9, 3, 3))
        
    def forward(self, x):
        # = torch.bmm(torch.pow(self.weights, self.num_iter), x.unsqueeze(2)).squeeze(2)
        x = torch.matmul(self.weights, x.transpose_(0, 1))
        return x

In [14]:
class Encoder(nn.Module):
    
    def __init__(self, num_channel):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=num_channel, out_channels=16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(16, 8, 3, padding=1)
        self.conv3 = nn.Conv2d(8, 8, 3, padding=1)
        self.conv4 = nn.Conv2d(8, 8, 2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(200, 128)
        self.fc2 = nn.Linear(128, 3)
        self.mmc = MMC()
    
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = self.pool(F.relu(self.conv4(x)))
        x = x.view(-1, 5*5*8)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        print('before: ', x)
        x = self.mmc(x)
        print('after: ', x)
        return x

In [15]:
model = Encoder(1)
for n, p in model.named_parameters():
    print(n, p.shape)

conv1.weight torch.Size([16, 1, 3, 3])
conv1.bias torch.Size([16])
conv2.weight torch.Size([8, 16, 3, 3])
conv2.bias torch.Size([8])
conv3.weight torch.Size([8, 8, 3, 3])
conv3.bias torch.Size([8])
conv4.weight torch.Size([8, 8, 2, 2])
conv4.bias torch.Size([8])
fc1.weight torch.Size([128, 200])
fc1.bias torch.Size([128])
fc2.weight torch.Size([3, 128])
fc2.bias torch.Size([3])
mmc.weights torch.Size([3, 3])


In [16]:
# summary(model, (1, 100, 100))

In [17]:
def get_model(num_channel):
    
    net = Encoder(num_channel=num_channel)
    optimizer = torch.optim.Adam(net.parameters(), lr=0.001)
    
    return net, optimizer

In [18]:
def to_tensor(x):
    return torch.from_numpy(x).float()

def get_data(height, width, num_channel, path, size, bs):
    
    dgen = DataGen(height, width, num_channel)
    x, y = dgen.get_data(path, True, size, True)
    print('Data loaded...\nx:{}\ty:{}\n'.format(x.shape, y.shape))
    
    x = x / 255.
    x = x[:90]
    y = y[:90]
    
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, shuffle=True)
    x_train, x_test, y_train, y_test = map(to_tensor, (x_train, x_test, y_train, y_test))
    
    train_ds = TensorDataset(x_train, y_train)
    train_dl = DataLoader(train_ds, batch_size=bs, shuffle=True)

    test_ds = TensorDataset(x_test, y_test)
    test_dl = DataLoader(test_ds, batch_size=bs)
    
    return train_dl, test_dl

In [19]:
def grad_flow(named_parameters):
    ave_grads = []
    max_grads= []
    layers = []
    for n, p in named_parameters:
        if(p.requires_grad) and ("bias" not in n):
            layers.append(n)
            ave_grads.append(p.grad.abs().mean())
            max_grads.append(p.grad.abs().max())
    print('layers: {}'.format(layers))
    print('max: {}'.format(max_grads))
    print('mean: {}\n\n'.format( ave_grads))

In [20]:
def fit(net, optimizer, train_dl, test_dl, epochs):
    
    loss_function = nn.MSELoss()
    for epoch in range(epochs):
        net.train()
        for x, y in train_dl:
            pred = net(x)
            loss = loss_function(pred, y)

            optimizer.zero_grad()
            loss.backward()
            # grad_flow(net.named_parameters())
            optimizer.step()

        net.eval()
        with torch.no_grad():
            test_loss = sum(loss_function(net(x), y) for x, y in test_dl)
        print('epoch:{}, test_loss:{}'.format(epoch+1, test_loss/len(test_dl)))

In [21]:
DATA_DIR = './data/data_simple_movement/'
HEIGHT = 100
WIDTH = 100
NUM_CHANNEL = 2

In [22]:
net, optimizer = get_model(num_channel=2)

train_dl, test_dl = get_data(
    height=HEIGHT, 
    width=WIDTH,
    num_channel=NUM_CHANNEL,
    path=DATA_DIR,
    size=8,
    bs=1
)

fit(net, optimizer, train_dl, test_dl, epochs=100)

Data loaded...
x:(96, 2, 100, 100)	y:(96, 3)

before:  tensor([[-0.0334,  0.0259, -0.0625]], grad_fn=<AddmmBackward>)
after:  tensor([[-0.0282],
        [-0.0292],
        [-0.0625]], grad_fn=<MmBackward>)
before:  tensor([[-0.0275,  0.0297, -0.0300]], grad_fn=<AddmmBackward>)
after:  tensor([[-0.0215],
        [-0.0025],
        [-0.0300]], grad_fn=<MmBackward>)
before:  tensor([[-0.0148,  0.0325,  0.0053]], grad_fn=<AddmmBackward>)
after:  tensor([[-0.0083],
        [ 0.0201],
        [ 0.0053]], grad_fn=<MmBackward>)
before:  tensor([[0.0018, 0.0360, 0.0483]], grad_fn=<AddmmBackward>)
after:  tensor([[0.0090],
        [0.0465],
        [0.0483]], grad_fn=<MmBackward>)
before:  tensor([[0.0176, 0.0413, 0.0968]], grad_fn=<AddmmBackward>)
after:  tensor([[0.0259],
        [0.0792],
        [0.0968]], grad_fn=<MmBackward>)
before:  tensor([[0.0376, 0.0469, 0.1530]], grad_fn=<AddmmBackward>)
after:  tensor([[0.0470],
        [0.1154],
        [0.1530]], grad_fn=<MmBackward>)
before:  ten

KeyboardInterrupt: 

In [13]:
for x, y in test_dl:
    print('prediction: {}, target: {}'.format(net(x), y))

prediction: tensor([[1.5738],
        [1.5649],
        [1.5988]], grad_fn=<MmBackward>), target: tensor([[2.3503, 0.0082, 2.3562]])
prediction: tensor([[0.3144],
        [0.3077],
        [0.3060]], grad_fn=<MmBackward>), target: tensor([[0.7834, 0.0027, 0.7854]])
prediction: tensor([[1.0492],
        [1.0388],
        [1.0842]], grad_fn=<MmBackward>), target: tensor([[1.5669, 0.0054, 1.5708]])
prediction: tensor([[1.5840],
        [1.5703],
        [1.6074]], grad_fn=<MmBackward>), target: tensor([[2.3503, 0.0082, 2.3562]])
prediction: tensor([[0.5493],
        [0.5370],
        [0.5649]], grad_fn=<MmBackward>), target: tensor([[1.0446, 0.0036, 1.0472]])
prediction: tensor([[0.1723],
        [0.1767],
        [0.1480]], grad_fn=<MmBackward>), target: tensor([[0.2611, 0.0009, 0.2618]])
prediction: tensor([[0.3171],
        [0.3109],
        [0.3056]], grad_fn=<MmBackward>), target: tensor([[0.7834, 0.0027, 0.7854]])
prediction: tensor([[1.5730],
        [1.5656],
        [1.6028]], gr

In [11]:
a = np.array([[-0.0472], [-0.0123],  [0.0237]])
b = np.array([[1, 0.2, 0], [-1, 0, 1], [0, 0, 1]])
np.dot(b, a)

array([[-0.04966],
       [ 0.0709 ],
       [ 0.0237 ]])

In [11]:
#         iteration = 0
#         while iteration < self.num_iter:
#             for i in range(x.shape[0]):
#                 x[i] = torch.matmul(self.weights, x[i])
#             iteration += 1
        # x = torch.acos(x)

In [20]:
a = torch.tensor([[1, 2, 3]])
a

tensor([[1, 2, 3]])

In [21]:
a.transpose(0, 1)

tensor([[1],
        [2],
        [3]])